name: lint
run-name: ${{ github.actor }} is linting the package

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  lints:
    name: Ruff, Pyright, and Codespell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use latest checkout action

      - name: Run Codespell
        uses: codespell-project/actions-codespell@v2

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && uv --version

      - name: Set Up Python Environment (using uv)
        run: uv python install 3.10

      - name: Restore uv cache
        uses: actions/cache@v4
        id: uv-cache
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }} # Key based on lock file if exists, else pyproject
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install dependencies (including dev, lint, typecheck extras)
        run: uv sync --all-extras --dev

      - name: Run Ruff (Check & Format Check)
        run: uv run ruff check . && uv run ruff format --check .

      - name: Run Pyright (Type Check)
        run: uv run pyright sandbox

